### ISSUE TITLE
As a user, I want to be able to challenge other users to Elo-rated matches

### ISSUE THREAD

**Issue by alaindupuis-introhive** [alexinman/elo-slack-app#1]
Technical details: 
- A user will be able to initiate challenges by using the command
**/elo challenge @recipient_username gametype**
- ~> A message will be sent to the challenge recipient that they have been directly challenged by **@sender_username**, with perhaps a message saying what their Elo rating delta will be if they win/lose (@alexinman ?)
- ~> Recipient will be able to accept or deny the challenge by using the same command:
**/elo challenge @sender_username gametype**
which will alert the challenge sender and all relevant channels (**#gametype**)
- A user will be able to withdraw existing challenges by using the command
**/elo unchallenge @recipient_username gametype**
- ~> A message will be sent to the challenge recipient that the challenge has been withdrawn

Definition of done:
- When someone uses the challenge command, we just look up existing challenges with the given details, **if** a challenge already exists **and** was initiated by a different party **then** accept the challenge and announce the acceptance.
- If there is an existing challenge and the sender types the challenge command, Elo will display a short message saying that the challenge has already been initiated, with instructions on how to cancel a challenge.
- If no such challenge exists, initiate a new challenge.

**Comment by alexinman** [comment]
Needs Technical Details and Definition of done.

**Comment by adupuis2** [comment]
Looking at implementation of this, I am thinking it might be necessary to establish another table if we want to properly track all statistics.

`id: int
challenger: players.id #not null
recipient: players.id #not null
game: Games.id #default null
status: Challenge::StatusCode #enum: [initiated, accepted, rejected, completed]`

Otherwise, we could just keep all active challenges in application memory. My concern with that is the challenges may be lost/reset when the Dyno is put to sleep, and we would want them to persist indefinitely for good UX with the Slack button integration.

Input @alexinman ?

**Comment by alexinman** [comment]
Yea, I think that would be a good idea. One small change, the columns that are fks to the players table should have `_id` at the end (e.g. `challenger_id`).

**Comment by adupuis2** [comment]
My hand got bit by a dog today, so I put in a little work on this story instead of documenting setup of a local dev env.

**Comment by alexinman** [comment]
`/elo @mike.waugh and @matthew.jones challenge @alex.inman and @ryker.hatch at pingpong`
