### ISSUE TITLE
As a user, I would like to have elo recommend a random challenge for me

### ISSUE THREAD

**Issue by mwaugh** [alexinman/elo-slack-app#17]
`/elo who should @username challenge at <game>` would produce a list of recommendations of people to play. 

The algorithm could take into consideration people that the challenger seldom plays, greatest possible elo award, etc.

Bonus points if there are actionable slack buttons to click by each of the challenger names to invoke the `challenge` feature as per #1

**Comment by alexinman** [comment]
I think we'll split that last part out into a something separate we can tackle after #1 is complete unless this isn't implemented until after #1 is complete. 

A possible list of challengers could include:
- Most to gain (essentially rank 1, unless you're rank 1... @mwaugh :eyes:)
- Easiest win (essentially lowest rank, but only if their rating is close enough to yours so that you'd actually gain something when you win)
- Seldom/never played (A player that you've never played or the player you've played the least)
- Similar rating (The player with the closest rating to yours)
